### ISSUE TITLE
Clarify community guidelines

### ISSUE THREAD

**Issue by jdmoorman** [mengaldo/PySPOD#12]
The statement regarding community guidelines in the README could be clearer. For reference:

> Contact me by email for further information or questions about PySPOD, or suggest pull requests. Contributions improving code and documentation, as well as suggestions about new features are more than welcome!

- [x] The guidelines should be in their own section(s) since a third party would not think to look in **Authors and contributors** for instructions on contributing.
- [x] Please explicitly address how users should report issues or problems with the software.
- [x] Please make "contact me" a link as in the **Recent works with PySPOD** section.
- [x] "..., or suggest pull requests." seems out of place since pull requests are not a natural way of requesting information or asking questions.

**Comment by jdmoorman** [comment]
[openjournals/joss-reviews#2862](https://github.com/openjournals/joss-reviews/issues/2862)

**Comment by mengaldo** [comment]
Thank you @jdmoorman, I should have addressed this issue - please, let me know if there is anything else I could improve in terms of community guidelines.
