### ISSUE TITLE
The usage examples shown in tutorials/ could present more detailed information about how to employ the SPOD output in further analysis

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [mengaldo/PySPOD#13]
Although the examples of tutorials/ are very detailed about the instantiation and execution of the library PySPOD itself, it seems that a more deepened explanation on how to employ the SPOD output in further analysis or applications (for instance, to feed a machine learning model, if applicable) could be interesting to better introduce a unacquainted user.

**Comment by mengaldo** [comment]
Thank you @Joao-L-S-Almeida, I am working on adding projections, in order to show how to use the output. Once completed, I will comment here again.
