### ISSUE TITLE
How to reconstruct original data with Pyspod, in the time domain?

### ISSUE THREAD

**Issue by bva99** [mengaldo/PySPOD#15]
I am trying to apply spectral POD to a mean-normalized data matrix **Q**(t,**x**)&isin;&#8477;<sup>N&times;M</sup>, where N is the number of variables times the number of spatial grid points and M is the number of snapshots.

In classical POD, we find the K modes **&Psi;**(**x**)&isin;&#8477;<sup>N&times;K</sup>, either through the eigenvectors of the covariance matrix or of the correlation matrix, and then define the time-amplitudes **A**(t)&isin;&#8477;<sup>K&times;M</sup> that approximates **Q** via **A**=**&Psi;**<sup>t</sup> **Q**.

Thus, the reconstructed (mean-normalized) data in classical POD is **Q&#771;**=**&Psi;** **A**

But this is not clear to me in SPOD. Specifically, I have two main questions on using Pyspod, which I believe are missing in the tutorials:
#### 1) How does one obtain the equivalent (spectral?)matrix **Â** in SPOD? Is there one matrix for each frequency _f_<sub>k</sub>?
I imagine it would be **Â**<sub>_k_</sub>=**&Psi;&#770;**<sup>t</sup><sub>_k_</sub> **Q&#770;**<sub>_k_</sub>
#### 2) How do I get the approximation of **Q&#771;** in the time domain, once I have the equivalent reconstructed matrix in the frequency domain?
Do I need to perform a "block inverse FFT"?

PS.: I really wish Github supported LateX notation hahaha

**Comment by mengaldo** [comment]
@bva99 thank you for the note. I am trying to get that implemented that shortly. To answer to your questions, yes, that is what you need to do, and there is a paper about to appear from @olivertschmidt that will explain that in detail. 

1.) for every frequency:  **A**=**&Psi;**<sup>t</sup> **W** **Q**.
2.) q<sup>(k)</sup> = (1 / W) * ifft(<sup>(k, freq)</sup>)

**Comment by mengaldo** [comment]
@bva99  this is now present in the main branch of the code. You can check the code in spod_base.py, methods: ```reconstruct_data``` and ```reconstruct_data_freq```. These two methods follow "[Frequency–time analysis, low-rank reconstruction and denoising of turbulent flows using SPOD](https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/article/frequencytime-analysis-lowrank-reconstruction-and-denoising-of-turbulent-flows-using-spod/185209DE4D89853B8F3F2D4B9305EFDD)".
