### ISSUE TITLE
ffmpeg dependency

### ISSUE THREAD

**Issue by jdmoorman** [mengaldo/PySPOD#5]
The ffmpeg dependency mentioned in the [README](https://github.com/mengaldo/PySPOD#installation-and-dependencies) is not the same as the ffmpeg requirement listed in `setup.py` on line 28. The ffmpeg requirement listed in `setup.py` is actually [https://pypi.org/project/ffmpeg/](https://pypi.org/project/ffmpeg/). There is a Python wrapper for ffmpeg called [ffmpy](https://pypi.org/project/ffmpy/) that you might be able to use, or you can link to [ffmpeg.org](https://ffmpeg.org/download.html) so users know where to download ffmpeg. In any case, ffmpeg should be removed from the requirements list in `setup.py`.

**Comment by jdmoorman** [comment]
[openjournals/joss-reviews#2862](https://github.com/openjournals/joss-reviews/issues/2862)

**Comment by mengaldo** [comment]
@jdmoorman This should now be fixed, thank you.
