### ISSUE TITLE
JOSS paper: State of the field

### ISSUE THREAD

**Issue by jdmoorman** [mengaldo/PySPOD#6]
Please discuss in the JOSS paper how this software compares to other commonly-used packages in the field. In particular, be sure to explain 

- [x] how SPOD compares other SVD based techniques and 
- [x] how PySPOD compares to other SPOD packages. 

A brief search for SPOD implementations turned up the following:

- https://gist.github.com/loiseaujc/dd3739fa779d7bdd678639ae7396a73b
- https://github.com/tjburrows/spod_python
- https://github.com/SpectralPOD/spod_matlab

**Comment by jdmoorman** [comment]
[openjournals/joss-reviews#2862](https://github.com/openjournals/joss-reviews/issues/2862)

**Comment by mengaldo** [comment]
@jdmoorman This has been addressed. Thank you.
