### ISSUE TITLE
JOSS paper: Quality of writing

### ISSUE THREAD

**Issue by jdmoorman** [mengaldo/PySPOD#7]
The JOSS paper is well-written. I have only a few minor comments and suggestions.

- [x] At the start of the third paragraph of the Summary section remove the comma after the word "While".
- [x] In the third paragraph of the Summary section, 

  > ... this library provides an efficient implementation of ...

  should say 

  > ... this library provides **efficient implementations** of ...

  since there are three implementations provided by the package.
- [x] In the third paragraph of the Summary section, remove the term "so-called" from the first sentence. The term "so-called" is usually used to imply that something is inappropriately named. If this was the intended meaning, please elaborate on why SPOD is not viewed as an appropriate name.
- [x] In the third paragraph of the Summary section, the first sentence can be broken into two shorter sentences to improve readability.
  > While, several variants of singular-value decomposition based techniques have been proposed in
the literature, this library provides an efficient implementation of the so-called spectral proper
orthogonal decomposition (SPOD) (Lumley, 2007), (Towne et al., 2017). SPOD is also referred
to as spectral empirical orthogonal function (SEOF) in the weather and climate community
(Schmidt et al., 2019).
- [x] In the first paragraph of the Capabilities section, please clarify the origin of each variant of SPOD listed in the first sentence. Are all three variants being attributed to (Schmidt & Towne, 2019) or just the streaming version?
- [x] In the first paragraph of the Capabilities section, change "large RAM" to "high RAM".
- [x] In the third paragraph of the Capabilities section, remove the duplicated word "figure" from the first sentence.
- [ ] In the third paragraph of the Capabilities section, the parenthetical abbreviations can be omitted since they are never used, unless some readers will only recognize the abbreviations.

**Comment by jdmoorman** [comment]
[openjournals/joss-reviews#2862](https://github.com/openjournals/joss-reviews/issues/2862)

**Comment by mengaldo** [comment]
@jdmoorman This should now be fixed. We kept the acronyms as they might be helpful to some readers.
